version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - fullstacknet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - fullstacknet

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    networks:
      - fullstacknet

networks:
  fullstacknet:

volumes:
  mongodata:
